- hosts: localhost
  become: no
  gather_facts: no
  vars_files:
    - node-config/nodes-ec2.yml
  roles:
    - ansible-role-ec2

  post_tasks:
    - name: add hosts to webserver group
      add_host:
        name: "{{ item.instances[0].public_ip_address }}"
        ansible_host: "{{ item.instances[0].public_ip_address }}"
        ansible_user: centos
        groups: tag_role_webserver,tag_app_lamp_multi_node
      loop: "{{ instances.results }}"
      when:
        - ('lamp_multi_node' in item.instances[0].tags.app)
        - ('webserver' in item.instances[0].tags.role)
      changed_when: no
      tags:
        - addhost

    - name: add hosts to dbserver group
      add_host:
        name: "{{ item.instances[0].public_ip_address }}"
        ansible_host: "{{ item.instances[0].public_ip_address }}"
        ansible_user: centos
        groups: tag_role_dbserver,tag_app_lamp_multi_node
      loop: "{{ instances.results }}"
      when:
        - ('lamp_multi_node' in item.instances[0].tags.app)
        - ('dbserver' in item.instances[0].tags.role)
      changed_when: no
      tags:
        - addhost

    - name: add hosts to lbserver group
      add_host:
        name: "{{ item.instances[0].public_ip_address }}"
        ansible_host: "{{ item.instances[0].public_ip_address }}"
        ansible_user: centos
        groups: tag_role_lbserver,tag_app_lamp_multi_node
      loop: "{{ instances.results }}"
      when:
        - ('lamp_multi_node' in item.instances[0].tags.app)
        - ('lbserver' in item.instances[0].tags.role)
      changed_when: no
      tags:
        - addhost

    - name: wait for connection
      wait_for_connection:
      delegate_to: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ instances.results }}"
      when: ('lamp_multi_node' in item.instances[0].tags.app)
      changed_when: no
      tags:
        - addhost